"""empty message

Revision ID: 56769446ed32
Revises: 97e9c2cac141
Create Date: 2025-08-30 20:56:53.170009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56769446ed32'
down_revision = '97e9c2cac141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('currently_open', sa.Boolean(), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('currently_open')
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
